elasticsearch:
  container_name: elasticsearch
  image: elasticsearch:latest
  command: elasticsearch 
  ports:
    - "9200:9200"
kibana:
  container_name: kibana
  image: kibana
  ports:
    - 5601:5601
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
    - elasticsearch
logstash:
  container_name: logstash
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - /mnt/workspace/docker-elk/logstash/conf:/etc/logstash/conf.d
    - /mnt/workspace/docker-elk/logstash/log:/var/log
  ports:
    - "12201:12201/udp"
  links:
    - elasticsearch